#!/bin/bash

function help {
    echo "Usage: rixmsg <function> [args]"
    echo ""
    echo "Functions:"
    echo "  help - Print this help message"
    echo "  show <rixmsg> - Show the defintion of a rixmsg"
    echo "  packages - List all packages"
    echo "  package <package name> - Show all messages in a package"
    echo "  create <path> - Create C++ header files from rixmsg files"
}

argc=$#
if [ $argc -eq 0 ] || [ $argc -gt 2 ]; then
    help
    exit 1
fi

# First argument is the function to call (help, show, packages, package, create)
func=$1
arg1=0
if [ $argc -eq 2 ]; then
    arg1=$2
fi

# Show the definition of a rixmsg
if [ $func == "show" ]; then
    # arg1 should be formatted as package/msg.rixmsg
    if [ $arg1 == 0 ]; then
        echo "Error: show function requires a rixmsg file as an argument"
        echo "Usage: rixmsg show <rixmsg>"
        exit 1
    fi

    package=$(echo $arg1 | cut -d'/' -f1 | tr '[:upper:]' '[:lower:]')
    msg=$(echo $arg1 | cut -d'/' -f2 | tr '[:upper:]' '[:lower:]')

    if [ ! -e /usr/local/include/rix/msg/defs/$package/$msg.rixmsg ]; then
        echo "Error: Package $package does not exist"
        exit 1
    fi

    cat /usr/local/include/rix/msg/defs/$package/$msg.rixmsg
    exit 0
fi

# List all packages
if [ $func == "packages" ]; then
    packages=$(ls /usr/local/include/rix/msg/defs)
    for package in $packages; do
        echo $package
    done
    exit 0
fi

# Show all messages in a package
if [ $func == "package" ]; then
    # arg1 should be the package name
    if [ $arg1 == 0 ]; then
        echo "Error: package function requires a package name as an argument"
        echo "Usage: rixmsg package <package name>"
        exit 1
    fi

    package=$(echo $arg1 | tr '[:upper:]' '[:lower:]')

    if [ ! -d /usr/local/include/rix/msg/defs/$package ]; then
        echo "Error: Package $package does not exist"
        exit 1
    fi

    msgs=$(ls /usr/local/include/rix/msg/defs/$package)
    for msg in $msgs; do
        echo $msg | cut -d'.' -f1
    done
    exit 0
fi

# Create C++ header files from rixmsg files
if [ $func == "create" ]; then
    # arg1 should be the path to the rixmsg files
    if [ $arg1 == 0 ]; then
        echo "Error: create function requires a path as an argument"
        echo "Usage: rixmsg create <path>"
        exit 1
    fi

    if [ ! -d $arg1 ]; then
        echo "Error: Path $arg1 does not exist"
        exit 1
    fi

    # Create the header files
    rixmsg-gen $arg1
    exit 0
fi