import unittest
import os

os.sys.path.append(os.path.dirname(os.path.abspath(__file__)) + "/../src")
from type_regex import (
    is_valid,
    is_static_array,
    is_dynamic_array,
    is_base_type,
    get_static_array_size,
    get_value_type,
)


class TestTypeRegex(unittest.TestCase):

    def test_valid(self):
        self.assertTrue(is_valid("a"))
        self.assertTrue(is_valid("A"))
        self.assertFalse(is_valid(""))
        self.assertFalse(is_valid("1"))
        self.assertFalse(is_valid("1my_type"))
        self.assertFalse(is_valid("1my_type[]"))
        self.assertFalse(is_valid("1[type]"))
        self.assertFalse(is_valid("1[]"))
        self.assertFalse(is_valid("_1"))
        self.assertFalse(is_valid("_1[]"))
        self.assertFalse(is_valid("_1[my_type]"))
        self.assertFalse(is_valid("_a"))
        self.assertFalse(is_valid("_"))

        self.assertTrue(is_valid("char"))
        self.assertTrue(is_valid("char[10]"))
        self.assertTrue(is_valid("char[]"))
        self.assertFalse(is_valid("char["))
        self.assertFalse(is_valid("char[10"))
        self.assertTrue(is_valid("char[10]"))

        self.assertTrue(is_valid("uint64"))
        self.assertTrue(is_valid("uint64[10]"))
        self.assertTrue(is_valid("uint64[]"))
        self.assertFalse(is_valid("uint64["))
        self.assertFalse(is_valid("uint64[10"))
        self.assertTrue(is_valid("uint64[10]"))

        self.assertTrue(is_valid("string"))
        self.assertTrue(is_valid("string[10]"))
        self.assertTrue(is_valid("string[]"))
        self.assertFalse(is_valid("string["))
        self.assertFalse(is_valid("str[ing"))
        self.assertFalse(is_valid("str[ing]"))
        self.assertFalse(is_valid("string[10"))
        self.assertTrue(is_valid("string[10]"))

        self.assertFalse(is_valid("123CustomType"))
        self.assertFalse(is_valid("123_Custom_Type"))
        self.assertTrue(is_valid("CustomType"))
        self.assertTrue(is_valid("Custom_Type"))
        self.assertTrue(is_valid("CustomType[10]"))
        self.assertTrue(is_valid("CustomType[]"))
        self.assertFalse(is_valid("CustomType["))
        self.assertFalse(is_valid("Custom[Type"))
        self.assertFalse(is_valid("Custom[Type]"))
        self.assertFalse(is_valid("CustomType[10"))
        self.assertTrue(is_valid("CustomType[10]"))

        self.assertFalse(is_valid("CustomType[string]"))
        self.assertFalse(is_valid("CustomType[string"))
        self.assertFalse(is_valid("CustomTypestring]"))
        self.assertFalse(is_valid("CustomType[uint16]"))
        self.assertFalse(is_valid("string[int64]"))
        self.assertFalse(is_valid("int64[string]"))
        self.assertFalse(is_valid("int64[CustomType]"))

    def test_static_array(self):
        self.assertFalse(is_static_array("char"))
        self.assertTrue(is_static_array("char[10]"))
        self.assertFalse(is_static_array("char[]"))
        self.assertFalse(is_static_array("char["))
        self.assertFalse(is_static_array("char[10"))
        self.assertTrue(is_static_array("char[10]"))

        self.assertFalse(is_static_array("uint64"))
        self.assertTrue(is_static_array("uint64[10]"))
        self.assertFalse(is_static_array("uint64[]"))
        self.assertFalse(is_static_array("uint64["))
        self.assertFalse(is_static_array("uint64[10"))
        self.assertTrue(is_static_array("uint64[10]"))

        self.assertFalse(is_static_array("string"))
        self.assertTrue(is_static_array("string[10]"))
        self.assertFalse(is_static_array("string[]"))
        self.assertFalse(is_static_array("string["))
        self.assertFalse(is_static_array("str[ing"))
        self.assertFalse(is_static_array("str[ing]"))
        self.assertFalse(is_static_array("string[10"))
        self.assertTrue(is_static_array("string[10]"))

        self.assertFalse(is_static_array("123CustomType"))
        self.assertFalse(is_static_array("123_Custom_Type"))
        self.assertFalse(is_static_array("CustomType"))
        self.assertFalse(is_static_array("Custom_Type"))
        self.assertTrue(is_static_array("CustomType[10]"))
        self.assertFalse(is_static_array("CustomType[]"))
        self.assertFalse(is_static_array("CustomType["))
        self.assertFalse(is_static_array("Custom[Type"))
        self.assertFalse(is_static_array("Custom[Type]"))
        self.assertFalse(is_static_array("CustomType[10"))
        self.assertTrue(is_static_array("CustomType[10]"))

        self.assertFalse(is_static_array("CustomType[string]"))
        self.assertFalse(is_static_array("CustomType[string"))
        self.assertFalse(is_static_array("CustomTypestring]"))
        self.assertFalse(is_static_array("CustomType[uint16]"))
        self.assertFalse(is_static_array("string[int64]"))
        self.assertFalse(is_static_array("int64[string]"))
        self.assertFalse(is_static_array("int64[CustomType]"))

    def test_dynamic_array(self):
        self.assertFalse(is_dynamic_array("char"))
        self.assertFalse(is_dynamic_array("char[10]"))
        self.assertTrue(is_dynamic_array("char[]"))
        self.assertFalse(is_dynamic_array("char["))
        self.assertFalse(is_dynamic_array("char[10"))
        self.assertFalse(is_dynamic_array("char[10]"))

        self.assertFalse(is_dynamic_array("uint64"))
        self.assertFalse(is_dynamic_array("uint64[10]"))
        self.assertTrue(is_dynamic_array("uint64[]"))
        self.assertFalse(is_dynamic_array("uint64["))
        self.assertFalse(is_dynamic_array("uint64[10"))
        self.assertFalse(is_dynamic_array("uint64[10]"))

        self.assertFalse(is_dynamic_array("string"))
        self.assertFalse(is_dynamic_array("string[10]"))
        self.assertTrue(is_dynamic_array("string[]"))
        self.assertFalse(is_dynamic_array("string["))
        self.assertFalse(is_dynamic_array("str[ing"))
        self.assertFalse(is_dynamic_array("str[ing]"))
        self.assertFalse(is_dynamic_array("string[10"))
        self.assertFalse(is_dynamic_array("string[10]"))

        self.assertFalse(is_dynamic_array("123CustomType"))
        self.assertFalse(is_dynamic_array("123_Custom_Type"))
        self.assertFalse(is_dynamic_array("CustomType"))
        self.assertFalse(is_dynamic_array("Custom_Type"))
        self.assertFalse(is_dynamic_array("CustomType[10]"))
        self.assertTrue(is_dynamic_array("CustomType[]"))
        self.assertFalse(is_dynamic_array("CustomType["))
        self.assertFalse(is_dynamic_array("Custom[Type"))
        self.assertFalse(is_dynamic_array("Custom[Type]"))
        self.assertFalse(is_dynamic_array("CustomType[10"))
        self.assertFalse(is_dynamic_array("CustomType[10]"))

        self.assertFalse(is_dynamic_array("CustomType[string]"))
        self.assertFalse(is_dynamic_array("CustomType[string"))
        self.assertFalse(is_dynamic_array("CustomTypestring]"))
        self.assertFalse(is_dynamic_array("CustomType[uint16]"))
        self.assertFalse(is_dynamic_array("string[int64]"))
        self.assertFalse(is_dynamic_array("int64[string]"))
        self.assertFalse(is_dynamic_array("int64[CustomType]"))

    def test_base_type(self):
        self.assertTrue(is_base_type("char"))
        self.assertTrue(is_base_type("char[10]"))
        self.assertTrue(is_base_type("char[]"))
        self.assertTrue(is_base_type("char["))
        self.assertTrue(is_base_type("char[10"))
        self.assertTrue(is_base_type("char[10]"))

        self.assertTrue(is_base_type("uint64"))
        self.assertTrue(is_base_type("uint64[10]"))
        self.assertTrue(is_base_type("uint64[]"))
        self.assertTrue(is_base_type("uint64["))
        self.assertTrue(is_base_type("uint64[10"))
        self.assertTrue(is_base_type("uint64[10]"))

        self.assertTrue(is_base_type("string"))
        self.assertTrue(is_base_type("string[10]"))
        self.assertTrue(is_base_type("string[]"))
        self.assertTrue(is_base_type("string["))
        self.assertFalse(is_base_type("str[ing"))
        self.assertFalse(is_base_type("str[ing]"))
        self.assertTrue(is_base_type("string[10"))
        self.assertTrue(is_base_type("string[10]"))

        self.assertFalse(is_base_type("123CustomType"))
        self.assertFalse(is_base_type("123_Custom_Type"))
        self.assertFalse(is_base_type("CustomType"))
        self.assertFalse(is_base_type("Custom_Type"))
        self.assertFalse(is_base_type("CustomType[10]"))
        self.assertFalse(is_base_type("CustomType[]"))
        self.assertFalse(is_base_type("CustomType["))
        self.assertFalse(is_base_type("Custom[Type"))
        self.assertFalse(is_base_type("Custom[Type]"))
        self.assertFalse(is_base_type("CustomType[10"))
        self.assertFalse(is_base_type("CustomType[10]"))

        self.assertFalse(is_base_type("CustomType[string]"))
        self.assertFalse(is_base_type("CustomType[string"))
        self.assertFalse(is_base_type("CustomTypestring]"))
        self.assertFalse(is_base_type("CustomType[uint16]"))
        self.assertTrue(is_base_type("string[int64]"))
        self.assertTrue(is_base_type("int64[string]"))
        self.assertTrue(is_base_type("int64[CustomType]"))

    def test_get_static_array_size(self):
        self.assertEqual(get_static_array_size("char[10]"), 10)
        self.assertEqual(get_static_array_size("uint64[10]"), 10)
        self.assertEqual(get_static_array_size("string[10]"), 10)
        self.assertEqual(get_static_array_size("CustomType[10]"), 10)
        self.assertEqual(get_static_array_size("char[100]"), 100)
        self.assertEqual(get_static_array_size("uint64[100]"), 100)
        self.assertEqual(get_static_array_size("string[100]"), 100)
        self.assertEqual(get_static_array_size("CustomType[100]"), 100)
        self.assertEqual(get_static_array_size("char[0]"), 0)
        self.assertEqual(get_static_array_size("uint64[0]"), 0)
        self.assertEqual(get_static_array_size("string[0]"), 0)
        self.assertEqual(get_static_array_size("CustomType[0]"), 0)
        self.assertEqual(get_static_array_size("char[]"), None)
        self.assertEqual(get_static_array_size("uint64[]"), None)
        self.assertEqual(get_static_array_size("string[]"), None)
        self.assertEqual(get_static_array_size("CustomType[]"), None)
        self.assertEqual(get_static_array_size("char"), None)
        self.assertEqual(get_static_array_size("uint64"), None)
        self.assertEqual(get_static_array_size("string"), None)
        self.assertEqual(get_static_array_size("CustomType"), None)
        self.assertEqual(get_static_array_size("CustomType[string]"), None)
        self.assertEqual(get_static_array_size("CustomType[uint16]"), None)
        self.assertEqual(get_static_array_size("string[int64]"), None)
        self.assertEqual(get_static_array_size("int64[string]"), None)
        self.assertEqual(get_static_array_size("int64[CustomType]"), None)

    def test_get_value_type(self):
        self.assertEqual(get_value_type("char[10]"), "char")
        self.assertEqual(get_value_type("uint64[10]"), "uint64")
        self.assertEqual(get_value_type("string[10]"), "string")
        self.assertEqual(get_value_type("CustomType[10]"), "CustomType")
        self.assertEqual(get_value_type("char[100]"), "char")
        self.assertEqual(get_value_type("uint64[100]"), "uint64")
        self.assertEqual(get_value_type("string[100]"), "string")
        self.assertEqual(get_value_type("CustomType[100]"), "CustomType")
        self.assertEqual(get_value_type("char[0]"), "char")
        self.assertEqual(get_value_type("uint64[0]"), "uint64")
        self.assertEqual(get_value_type("string[0]"), "string")
        self.assertEqual(get_value_type("CustomType[0]"), "CustomType")
        self.assertEqual(get_value_type("char[]"), "char")
        self.assertEqual(get_value_type("uint64[]"), "uint64")
        self.assertEqual(get_value_type("string[]"), "string")
        self.assertEqual(get_value_type("CustomType[]"), "CustomType")
        self.assertEqual(get_value_type("char"), "char")
        self.assertEqual(get_value_type("uint64"), "uint64")
        self.assertEqual(get_value_type("string"), "string")
        self.assertEqual(get_value_type("CustomType"), "CustomType")
        self.assertEqual(get_value_type("CustomType[string]"), "CustomType")
        self.assertEqual(get_value_type("CustomType[uint16]"), "CustomType")
        self.assertEqual(get_value_type("string[int64]"), "string")
        self.assertEqual(get_value_type("int64[string]"), "int64")
        self.assertEqual(get_value_type("int64[CustomType]"), "int64")


if __name__ == "__main__":
    unittest.main()
